- name: ensure ~/bin exists
  file:
    path: '{{ user_home_dir }}/bin'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ user_group_id }}'

- name: ~/bin/ files deployment
  synchronize:
    src: bin/
    dest: '{{ user_home_dir }}/bin/'
    archive: no
    checksum: yes
    compress: no
    recursive: yes
    rsync_opts:
      - "-gop"
      - "--chown={{ user }}:{{ user_group_id }}"
      - "--chmod=Fu=rwx,Fg=,Fo="
      - "--copy-links"
