- name: wireguard
  tags: [wireguard]
  block:
  - name: install wireguard via apt
    when: ansible_pkg_mgr == "apt"
    apt:
      name: wireguard
      state: present
      update_cache: yes

  - name: /etc/wireguard
    file:
      path: /etc/wireguard
      owner: root
      group: root
      mode: 0700
      state: directory

  - name: deploy configuration files
    include_tasks: service.yml
    with_fileglob: "{{ ansible_play_name }}/*.conf"
