- name: sshd
  tags: [sshd]
  block:
  - name: set sshd port
    when: network.sshd.port is defined
    lineinfile: 
      dest: /etc/ssh/sshd_config
      regexp: '^#?Port '
      line: 'Port {{ network.sshd.port }}'
      state: present
    notify: restart sshd
  
  - name: set PermitRootLogin to prohibit-password
    lineinfile: 
      dest: /etc/ssh/sshd_config
      regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin prohibit-password'
      state: present
    notify: restart sshd
  
  - name: set PasswordAuthentication to no
    lineinfile: 
      dest: /etc/ssh/sshd_config
      regexp: '^#?PasswordAuthentication'
      line: 'PasswordAuthentication no'
      state: present
    notify: restart sshd
  
  - name: set ChallengeResponseAuthentication to no
    lineinfile: 
      dest: /etc/ssh/sshd_config
      regexp: '^#?ChallengeResponseAuthentication'
      line: 'ChallengeResponseAuthentication no'
      state: present
    notify: restart sshd
  
  - name: autostart sshd
    service:
      name: sshd
      runlevel: "{{ 'default' if ansible_distribution == 'Gentoo' else omit }}"
      enabled: true
